services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  OpenOAP\OpenOap\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  OpenOAP\OpenOap\UserFunctions\FormEngine\TypeSelectItemsProcFunc:
    public: true

  OpenOAP\OpenOap\UserFunctions\FormEngine\DescendantsSelectItemsProcFunc:
    public: true

  OpenOAP\OpenOap\Command\CreateBackupCommand:
    tags:
      - name: 'console.command'
        command: 'open-oap:backup:create'
        description: 'Creates a complete backup of the TYPO3 installation.'

  OpenOAP\OpenOap\Command\CleanupTemporaryLinksCommand:
    tags:
      - name: 'console.command'
        command: 'open-oap:backup:cleanup-links'
        description: 'Removes expired temporary download links for backup files.'

  OpenOAP\OpenOap\Upgrades\ReplaceInvitationByNewWizard:
    tags:
      - name: install.upgradewizard
